### ISSUE TITLE
Did not compile on linux (Ubuntu 9.04) w/ signed int...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jaroslov/fcstools#4]
```
I have no real experience w/ C++ but do work mostly with Java.  I tried to
compile the latest version but found these errors:

g++ FCSConvert.cpp -O3 -I. -o fcsconvert
In file included from FCSConvert.cpp:8:
./FCSTools.hpp: In function ‘void FCSTools::truncate(FCS&, long int)’:
./FCSTools.hpp:109: error: call of overloaded ‘abs(long int&)’ is ambiguous
/usr/include/c++/4.3/cmath:99: note: candidates are: double std::abs(double)
/usr/include/c++/4.3/cmath:103: note:                 float std::abs(float)
/usr/include/c++/4.3/cmath:107: note:                 long double
std::abs(long double)
./FCSTools.hpp: In function ‘void FCSTools::truncate(FCS&, long int) [with
FCS = FCSTools::FCS<unsigned int>]’:
FCSConvert.cpp:161:   instantiated from here
./FCSTools.hpp:109: error: call of overloaded ‘abs(long int&)’ is ambiguous
/usr/include/c++/4.3/cmath:99: note: candidates are: double std::abs(double)
/usr/include/c++/4.3/cmath:103: note:                 float std::abs(float)
/usr/include/c++/4.3/cmath:107: note:                 long double
std::abs(long double)
make: *** [fcsconvert] Error 1

Solution? (don't know yet if it "breaks" the code functionality but at
least gets them compiled): convert signed int in "FCSTools::truncate" to
double.  I have attached the two modified files that now allow all tools to
compile for me...

```

Original issue reported on code.google.com by `douglas....@gmail.com` on 26 Jun 2009 at 10:42

Attachments:
- [FCSConvert.cpp](https://storage.googleapis.com/google-code-attachments/fcstools/issue-4/comment-0/FCSConvert.cpp)
- [FCSTools.hpp](https://storage.googleapis.com/google-code-attachments/fcstools/issue-4/comment-0/FCSTools.hpp)
